---
- name: Install fish shell
  community.general.homebrew:
    name: fish
    state: present

- name: Create fish config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: directory
    mode: '0755'

- name: Copy aliases file
  copy:
    src: "{{ playbook_dir }}/../.aliases.fish"
    dest: "{{ ansible_env.HOME }}/.config/fish/aliases.fish"
    mode: '0644'

- name: Add source aliases to fish config
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    line: "source ~/.config/fish/aliases.fish"
    create: yes
    mode: '0644'

- name: Disable fish greeting message
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    line: "set -g fish_greeting \"\""
    create: yes
    mode: '0644'
  tags: fish-greeting

- name: Get fish shell path
  command: which fish
  register: fish_path
  changed_when: false

- name: Check if fish is already in /etc/shells
  command: grep -Fxq "{{ fish_path.stdout }}" /etc/shells
  register: fish_in_shells
  changed_when: false
  failed_when: false

- name: Add fish to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ fish_path.stdout }}"
    state: present
  become: true
  become_method: sudo
  when: fish_in_shells.rc != 0

- name: Get current shell
  command: dscl . -read ~/ UserShell
  register: current_shell
  changed_when: false

- name: Change default shell to fish
  command: chsh -s {{ fish_path.stdout }} {{ ansible_env.USER }}
  register: shell_change
  changed_when: shell_change.rc == 0
  failed_when: shell_change.rc != 0
  when: fish_path.stdout not in current_shell.stdout