---
- name: Read brew packages from file
  command: cat {{ playbook_dir }}/../brew_packages.txt
  register: brew_packages_content
  changed_when: false

- name: Install brew packages
  community.general.homebrew:
    name: "{{ brew_packages_content.stdout_lines }}"
    state: present