# Register at https://openweathermap.org to get your API key
api_key = "<API_KEY>"

# This is for Wrocław, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "3081368"

# Display settings
units = "metric"
display_symbol = "°C"
